/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChannelsRouteRouteImport } from './routes/channels/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChannelsAtmeRouteImport } from './routes/channels/@me'
import { Route as ChannelsServerIdRouteRouteImport } from './routes/channels/$serverId/route'
import { Route as ChannelsServerIdIndexRouteImport } from './routes/channels/$serverId/index'
import { Route as ChannelsServerIdChannelIdRouteImport } from './routes/channels/$serverId/$channelId'

const ChannelsRouteRoute = ChannelsRouteRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsAtmeRoute = ChannelsAtmeRouteImport.update({
  id: '/@me',
  path: '/@me',
  getParentRoute: () => ChannelsRouteRoute,
} as any)
const ChannelsServerIdRouteRoute = ChannelsServerIdRouteRouteImport.update({
  id: '/$serverId',
  path: '/$serverId',
  getParentRoute: () => ChannelsRouteRoute,
} as any)
const ChannelsServerIdIndexRoute = ChannelsServerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChannelsServerIdRouteRoute,
} as any)
const ChannelsServerIdChannelIdRoute =
  ChannelsServerIdChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => ChannelsServerIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/channels/$serverId': typeof ChannelsServerIdRouteRouteWithChildren
  '/channels/@me': typeof ChannelsAtmeRoute
  '/channels/$serverId/$channelId': typeof ChannelsServerIdChannelIdRoute
  '/channels/$serverId/': typeof ChannelsServerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/channels/@me': typeof ChannelsAtmeRoute
  '/channels/$serverId/$channelId': typeof ChannelsServerIdChannelIdRoute
  '/channels/$serverId': typeof ChannelsServerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/channels/$serverId': typeof ChannelsServerIdRouteRouteWithChildren
  '/channels/@me': typeof ChannelsAtmeRoute
  '/channels/$serverId/$channelId': typeof ChannelsServerIdChannelIdRoute
  '/channels/$serverId/': typeof ChannelsServerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/channels/$serverId'
    | '/channels/@me'
    | '/channels/$serverId/$channelId'
    | '/channels/$serverId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/channels/@me'
    | '/channels/$serverId/$channelId'
    | '/channels/$serverId'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/channels/$serverId'
    | '/channels/@me'
    | '/channels/$serverId/$channelId'
    | '/channels/$serverId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRouteRoute: typeof ChannelsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels/@me': {
      id: '/channels/@me'
      path: '/@me'
      fullPath: '/channels/@me'
      preLoaderRoute: typeof ChannelsAtmeRouteImport
      parentRoute: typeof ChannelsRouteRoute
    }
    '/channels/$serverId': {
      id: '/channels/$serverId'
      path: '/$serverId'
      fullPath: '/channels/$serverId'
      preLoaderRoute: typeof ChannelsServerIdRouteRouteImport
      parentRoute: typeof ChannelsRouteRoute
    }
    '/channels/$serverId/': {
      id: '/channels/$serverId/'
      path: '/'
      fullPath: '/channels/$serverId/'
      preLoaderRoute: typeof ChannelsServerIdIndexRouteImport
      parentRoute: typeof ChannelsServerIdRouteRoute
    }
    '/channels/$serverId/$channelId': {
      id: '/channels/$serverId/$channelId'
      path: '/$channelId'
      fullPath: '/channels/$serverId/$channelId'
      preLoaderRoute: typeof ChannelsServerIdChannelIdRouteImport
      parentRoute: typeof ChannelsServerIdRouteRoute
    }
  }
}

interface ChannelsServerIdRouteRouteChildren {
  ChannelsServerIdChannelIdRoute: typeof ChannelsServerIdChannelIdRoute
  ChannelsServerIdIndexRoute: typeof ChannelsServerIdIndexRoute
}

const ChannelsServerIdRouteRouteChildren: ChannelsServerIdRouteRouteChildren = {
  ChannelsServerIdChannelIdRoute: ChannelsServerIdChannelIdRoute,
  ChannelsServerIdIndexRoute: ChannelsServerIdIndexRoute,
}

const ChannelsServerIdRouteRouteWithChildren =
  ChannelsServerIdRouteRoute._addFileChildren(
    ChannelsServerIdRouteRouteChildren,
  )

interface ChannelsRouteRouteChildren {
  ChannelsServerIdRouteRoute: typeof ChannelsServerIdRouteRouteWithChildren
  ChannelsAtmeRoute: typeof ChannelsAtmeRoute
}

const ChannelsRouteRouteChildren: ChannelsRouteRouteChildren = {
  ChannelsServerIdRouteRoute: ChannelsServerIdRouteRouteWithChildren,
  ChannelsAtmeRoute: ChannelsAtmeRoute,
}

const ChannelsRouteRouteWithChildren = ChannelsRouteRoute._addFileChildren(
  ChannelsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRouteRoute: ChannelsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
